// printing string and char literals

class Main {
	public void main() {
		Lib lib = new Lib();
		lib.printStr("abcdefghijklmnopqrstuvwxyz");
		lib.printStr("ABCDEFGHIJKLMNOPQRSTUVWXYZ");
		lib.printStr("1234567890");
		lib.printStr("`~!@#$%^&*()_+=-[]{}|;':,./<>?");
		lib.printStr("\n\t\\\'\" ");
		lib.printInt('a'); lib.printStr("\n");
		lib.printInt('b'); lib.printStr("\n");
		lib.printInt('c'); lib.printStr("\n");
		lib.printInt('d'); lib.printStr("\n");
		lib.printInt('e'); lib.printStr("\n");
		lib.printInt('f'); lib.printStr("\n");
		lib.printInt('g'); lib.printStr("\n");
		lib.printInt('h'); lib.printStr("\n");
		lib.printInt('i'); lib.printStr("\n");
		lib.printInt('j'); lib.printStr("\n");
		lib.printInt('k'); lib.printStr("\n");
		lib.printInt('l'); lib.printStr("\n");
		lib.printInt('m'); lib.printStr("\n");
		lib.printInt('n'); lib.printStr("\n");
		lib.printInt('o'); lib.printStr("\n");
		lib.printInt('p'); lib.printStr("\n");
		lib.printInt('q'); lib.printStr("\n");
		lib.printInt('r'); lib.printStr("\n");
		lib.printInt('s'); lib.printStr("\n");
		lib.printInt('t'); lib.printStr("\n");
		lib.printInt('u'); lib.printStr("\n");
		lib.printInt('v'); lib.printStr("\n");
		lib.printInt('w'); lib.printStr("\n");
		lib.printInt('x'); lib.printStr("\n");
		lib.printInt('y'); lib.printStr("\n");
		lib.printInt('z'); lib.printStr("\n");
		lib.printInt('A'); lib.printStr("\n");
		lib.printInt('B'); lib.printStr("\n");
		lib.printInt('C'); lib.printStr("\n");
		lib.printInt('D'); lib.printStr("\n");
		lib.printInt('E'); lib.printStr("\n");
		lib.printInt('F'); lib.printStr("\n");
		lib.printInt('G'); lib.printStr("\n");
		lib.printInt('H'); lib.printStr("\n");
		lib.printInt('I'); lib.printStr("\n");
		lib.printInt('J'); lib.printStr("\n");
		lib.printInt('K'); lib.printStr("\n");
		lib.printInt('L'); lib.printStr("\n");
		lib.printInt('M'); lib.printStr("\n");
		lib.printInt('N'); lib.printStr("\n");
		lib.printInt('O'); lib.printStr("\n");
		lib.printInt('P'); lib.printStr("\n");
		lib.printInt('Q'); lib.printStr("\n");
		lib.printInt('R'); lib.printStr("\n");
		lib.printInt('S'); lib.printStr("\n");
		lib.printInt('T'); lib.printStr("\n");
		lib.printInt('U'); lib.printStr("\n");
		lib.printInt('V'); lib.printStr("\n");
		lib.printInt('W'); lib.printStr("\n");
		lib.printInt('X'); lib.printStr("\n");
		lib.printInt('Y'); lib.printStr("\n");
		lib.printInt('Z'); lib.printStr("\n");
		lib.printInt('1'); lib.printStr("\n");
		lib.printInt('2'); lib.printStr("\n");
		lib.printInt('3'); lib.printStr("\n");
		lib.printInt('4'); lib.printStr("\n");
		lib.printInt('5'); lib.printStr("\n");
		lib.printInt('6'); lib.printStr("\n");
		lib.printInt('7'); lib.printStr("\n");
		lib.printInt('8'); lib.printStr("\n");
		lib.printInt('9'); lib.printStr("\n");
		lib.printInt('0'); lib.printStr("\n");
		lib.printInt('`'); lib.printStr("\n");
		lib.printInt('~'); lib.printStr("\n");
		lib.printInt('!'); lib.printStr("\n");
		lib.printInt('@'); lib.printStr("\n");
		lib.printInt('#'); lib.printStr("\n");
		lib.printInt('$'); lib.printStr("\n");
		lib.printInt('%'); lib.printStr("\n");
		lib.printInt('^'); lib.printStr("\n");
		lib.printInt('&'); lib.printStr("\n");
		lib.printInt('*'); lib.printStr("\n");
		lib.printInt('('); lib.printStr("\n");
		lib.printInt(')'); lib.printStr("\n");
		lib.printInt('_'); lib.printStr("\n");
		lib.printInt('+'); lib.printStr("\n");
		lib.printInt('='); lib.printStr("\n");
		lib.printInt('-'); lib.printStr("\n");
		lib.printInt('['); lib.printStr("\n");
		lib.printInt(']'); lib.printStr("\n");
		lib.printInt('{'); lib.printStr("\n");
		lib.printInt('}'); lib.printStr("\n");
		lib.printInt('|'); lib.printStr("\n");
		lib.printInt(';'); lib.printStr("\n");
		lib.printInt('"'); lib.printStr("\n");
		lib.printInt(':'); lib.printStr("\n");
		lib.printInt(','); lib.printStr("\n");
		lib.printInt('.'); lib.printStr("\n");
		lib.printInt('/'); lib.printStr("\n");
		lib.printInt('<'); lib.printStr("\n");
		lib.printInt('>'); lib.printStr("\n");
		lib.printInt('?'); lib.printStr("\n");
		lib.printInt('\n'); lib.printStr("\n");
		lib.printInt('\t'); lib.printStr("\n");
		lib.printInt('\\'); lib.printStr("\n");
		lib.printInt('\''); lib.printStr("\n");
		lib.printInt('\"'); lib.printStr("\n");
		lib.printInt(' '); lib.printStr("\n");
	}
	
}
